# Generated by Django 3.1 on 2021-08-19 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_sevekari_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='sampark_sevekari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sscode', models.CharField(max_length=5)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='sevekari_new',
        ),
    ]
