# Generated by Django 3.1 on 2021-08-21 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20210819_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='session_data',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('prashan1', models.CharField(max_length=200)),
                ('prashan2', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(default='submitted', max_length=30)),
                ('Date_filled', models.DateField(auto_now=True)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
