# Generated by Django 3.1 on 2021-08-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_session_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampark_sevekari',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
