# Generated by Django 3.1 on 2021-08-27 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_sampark_sevekari_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampark_sevekari',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='seva_data',
            fields=[
                ('seva_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_qa', models.DateField(auto_now=True)),
                ('seva1', models.CharField(default=None, max_length=150)),
                ('seva2', models.CharField(default=None, max_length=150)),
                ('seva3', models.CharField(default=None, max_length=150)),
                ('seva4', models.CharField(default=None, max_length=150)),
                ('seva5', models.CharField(default=None, max_length=150)),
                ('seva6', models.CharField(default=None, max_length=150)),
                ('seva7', models.CharField(default=None, max_length=150)),
                ('seva8', models.CharField(default=None, max_length=150)),
                ('seva9', models.CharField(default=None, max_length=150)),
                ('seva10', models.CharField(default=None, max_length=150)),
                ('seva11', models.CharField(default=None, max_length=150)),
                ('seva12', models.CharField(default=None, max_length=150)),
                ('seva13', models.CharField(default=None, max_length=150)),
                ('seva14', models.CharField(default=None, max_length=150)),
                ('seva15', models.CharField(default=None, max_length=500)),
                ('status1', models.BooleanField(default=False)),
                ('status2', models.BooleanField(default=False)),
                ('status3', models.BooleanField(default=False)),
                ('status4', models.BooleanField(default=False)),
                ('status5', models.BooleanField(default=False)),
                ('status6', models.BooleanField(default=False)),
                ('status7', models.BooleanField(default=False)),
                ('status8', models.BooleanField(default=False)),
                ('status9', models.BooleanField(default=False)),
                ('status10', models.BooleanField(default=False)),
                ('status11', models.BooleanField(default=False)),
                ('status12', models.BooleanField(default=False)),
                ('status13', models.BooleanField(default=False)),
                ('status14', models.BooleanField(default=False)),
                ('status15', models.BooleanField(default=False)),
                ('seva_status', models.CharField(default='inprogress', max_length=15)),
                ('anubhav', models.BooleanField(default=False)),
                ('sahitya', models.BooleanField(default=False)),
                ('seva_explained', models.BooleanField(default=False)),
                ('guru_ans_p1', models.CharField(default=None, max_length=15)),
                ('guru_ans_p2', models.BooleanField(default=None, max_length=15)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.session_data')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
