# Generated by Django 3.1 on 2021-08-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20210827_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_data',
            name='Date_filled',
            field=models.CharField(default='2021-08-30', max_length=150),
        ),
    ]
