# Generated by Django 3.1 on 2021-08-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20210830_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seva_data',
            name='guru_ans_p2',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
